#pragma once
class CComponet;
class CAttitude;
class COrbit;
class CAttitudeController;
class Environment;
class GyroScope;
class Quat;
class CDcm;
class CEulerAgl;
class CConfig;
class CSimTime;
class Satellite;
class CInfluxDB;
class StarSensor;
class SunSensor;
class GNSS;